### ISSUE TITLE
O usuário consegue digitar uma sugestão que não está dentro dos valores mínimo e máximo

### ISSUE THREAD

**Issue by ArlysthonFeitosa** [JuliaaNasc/Sorteio-da-sorte#2]
Nessa situação:
Mínimo = 10
Máximo = 20

O sistema ainda deixa o usuário digitar um valor que não está entre 10 e 20.
Acredito que isso é uma falha.

**Comment by JuliaaNasc** [comment]
Obrigada pela sugestão na melhoria do código. Já foi corrigido!
