### ISSUE TITLE
Histórico de partidas

### ISSUE THREAD

**Issue by ArlysthonFeitosa** [JuliaaNasc/Sorteio-da-sorte#4]
Seria interessante se o usuário conseguisse visualizar o histórico de partidas.

**Comment by JuliaaNasc** [comment]
Obrigada pela dica!
já foi atualizado isso no código, mostrando a quantidade de partidas já rodadas até acertar, e no momento que acertar, pergunta se quer continuar, ver histórico de partidas (n* mínimo/ n* máximo/ tentativas/ número sorteado), ou parar o código mesmo.
